# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: dotnet-tool-restore
        name: dotnet-tool-restore
        entry: dotnet tool restore
        language: system
        always_run: true
        pass_filenames: false
        stages:
          - commit
          - push
          - post-merge
        description: Install the .NET tools listed at .config/dotnet-tools.json.
      - id: branch-name-format
        name: check format of branch name
        language: system
        entry: scripts/pre-commit-branch-name-hook.sh
        
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        exclude: ^data/.*
      - id: check-added-large-files
        exclude: src/Infrastructure/Terminology/SnomedCodes.json
      - id: check-json
        exclude: ^data/.* | ^templates/.*
      - id: detect-private-key
        exclude: |
          (?x)^(
              data/.*|
              .*TokenFactoryTests.cs
          )$

  - repo: https://github.com/dotnet/format
    rev: v8.0.453106
    hooks:
      - id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format --verbosity diagnostic --include
        exclude: ^data/.*
        types_or: ["c#"]
        
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
