variable "location" {}
variable "resource_group_name" {}
variable "vnet_id" {}
variable "app_plan_subnet_id" {}
variable "services_subnet_id" {}
variable "env" {}
variable "runner_ip" {}
variable "acr_zone_id" {}
variable "app_zone_id" {}
variable "tenant_id" {}
variable "image_tag_suffix" {}
variable "fhir_url" {}
variable "app_insights_instrumentation_key" {}
variable "current_object_id" {}
variable "vault_zone_id" {}
variable "storage_zone_id" {}
variable "sp_client_id" {}
variable "shared_resource_group_name" {}